### ISSUE TITLE
Batch-Processing: Progress window gets 'active' for each step that is calculated 

### ISSUE THREAD

**Issue by simschul** [softwareschneiderei/bwinpro#2]
**Describe the bug**
When running bwinpro in the batch mode the window "Progress" is opened. However, when you want to change to another open application (e.g. your browser) while the batch process is still running, the bwinpro window activates itself everytime a new step is calculated.  

bwinpro v7.8-04

**To Reproduce**
1. Go to 'Stand --> open --> open access db'
2. Click on 'calc all follow the instruction'
3. Change to another open applicatioin (e.g. your browser)
4. after a few seconds you automatically come back to bwinpro

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by miq** [comment]
I see what you mean. Try to resolve the issue soon.

**Comment by miq** [comment]
Fixed it by setting autoRequestFocus to false for this dialog.
